# Generated by Django 5.0.3 on 2024-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0004_donar_donarmanagement_silentauction'),
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='donar',
            field=models.ManyToManyField(related_name='donar', through='eventapi.DonarManagement', to='eventapi.donar'),
        ),
    ]
