# Generated by Django 5.0.3 on 2024-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0005_event_biditem_eventimages'),
        ('userapi', '0002_customuser_donar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donar',
            field=models.ManyToManyField(related_name='donars', through='eventapi.DonarManagement', to='eventapi.donar'),
        ),
    ]
