# Generated by Django 5.0.3 on 2024-04-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0004_donar_donarmanagement_silentauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='biditem',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapi.event')),
            ],
        ),
    ]
