# Generated by Django 5.0.3 on 2024-04-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0005_event_biditem_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_raffle',
            field=models.BooleanField(default=False),
        ),
    ]
