# Generated by Django 5.0.3 on 2024-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0006_event_is_raffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_raffle',
            field=models.BooleanField(default=True),
        ),
    ]
