# Generated by Django 5.0.3 on 2024-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapi', '0007_alter_event_is_raffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_raffle',
            field=models.BooleanField(default=False),
        ),
    ]
